# Generated by Django 3.0.4 on 2020-04-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, max_length=50, upload_to=''),
            preserve_default=False,
        ),
    ]
